- tiberius/examples/new.rs
- tiberius/src/client.rs
- tiberius/src/client/connection.rs
- tiberius/src/protocol/stream/prepared.rs
- tiberius/src/protocol/stream/query.rs
- tiberius/src/protocol/stream/token.rs
- tiberius/tests/query.rs
Dirty streams done dirt cheap.
> Flush streams clean before use

- tiberius/src/client/connection.rs
- tiberius/src/protocol/codec/decode.rs
- tiberius/src/tls.rs
Tested on Azure SQL with TLS enabled.
> TDS packet handling on TLS handshake

- Cargo.toml
- examples/new.rs
- src/client.rs
- src/lib.rs
- src/macros.rs
- src/row.rs
- src/tds/codec/column_data.rs
- src/tds/numeric.rs
- src/tds/stream/query.rs
- src/tds/xml.rs
- src/to_sql.rs
- tests/query.rs
Should solve https://github.com/prisma/tiberius/issues/31
> Numeric decimal

- .buildkite/docker.sh
- src/client.rs
- src/client/builder.rs
- src/client/connection.rs
- src/client/tls.rs
- src/error.rs
- src/lib.rs
- src/macros.rs
- src/result.rs
- src/row.rs
- src/tds.rs
- src/tds/numeric.rs
- src/tds/stream/prepared.rs
- src/tds/stream/query.rs
- src/to_sql.rs
Warnings:
- All public items must be documented
- All public items must implement `Debug`
- Must follow Rust 2018 idioms
Errors:
- In tests, deny warnings
- In tests, deny idions that do not follow Rust 2018 guidelines
- In tests, allow unused extern crates
- In tests, allow unused variables
> Enforcing lints.

- src/result.rs
- src/tds/codec/token/token_env_change.rs
- src/tds/collation.rs
- src/tds/stream/query.rs
- src/tds/stream/token.rs
- src/to_sql.rs
> Add Send + Sync boundaries for parameters

- src/client.rs
- src/client/auth.rs
- src/client/connection.rs
- src/row.rs
- src/sql_read_bytes.rs
- src/tds.rs
- src/tds/codec/token/token_row.rs
- src/tds/stream/token.rs
> Refactoring

- Cargo.toml
- src/client/builder.rs
- src/lib.rs
- src/sql_browser.rs
- src/tds/time.rs
Also allows using the SQL Browser on all platforms.
> Library level documentation for basic use-cases

- .buildkite/pipeline.sh
- src/tds/time.rs
- tests/query.rs
Fixes https://github.com/prisma/tiberius/issues/45
> Fix chrono functionality for SQL Server 2005

- src/client/connection.rs
Some implementations of `NextBytes` on Windows platforms do not implement `Send`, meaning the `Connection` is not `Send` and it gets quite complex to use the `Client` in places where `Send` is required. This change is not the prettiest, but at least should fix the issue.
> Reconstruct the login process to not lose `Send` on Windows platforms for `Connection`

- src/tds/codec/token/token_col_metadata.rs
In some cases the table name metadata comes in multiple parts. This caused corrupted data when reading the `IMAGE` type, and the PR should fix the bug in https://github.com/prisma/tiberius/issues/56.
> Table name can be in multiple parts

- Cargo.toml
- README.md
- src/client.rs
- src/from_sql.rs
- src/lib.rs
- src/macros.rs
- src/tds/numeric.rs
- src/tds/time.rs
- src/tds/time/chrono.rs
- src/to_sql.rs
- tests/query.rs
Should address the issue https://github.com/prisma/tiberius/issues/59
> Document conversions between Rust and SQL Server

- examples/async-std.rs
- examples/tokio.rs
- src/client/connection.rs
- src/tds/stream/query.rs
- tests/named-instance-tokio.rs
- tests/query.rs
> skip any recieved done_rows amounts and avoid creating extra resultsets

- tests/query.rs
Also none of the chrono tests were running...
> More chrono tests

- src/tds/codec/column_data.rs
- src/tds/time.rs
> Fix null time/datetime2/dtoffset handling

- Cargo.toml
> add dns feature to tokio

- src/from_sql.rs
- tests/query.rs
A fix looks a bit dirty, but hopefully this will help to better understand the issue.
> Handling nullable int values, fix for #78

- src/client/builder.rs
- src/client/connection.rs
- src/error.rs
- src/tds/codec/token/token_env_change.rs
- src/tds/stream/token.rs
Returns an error in connection if getting a `Routing` token. The user needs to reconnect to the new address.
Closes: https://github.com/prisma/tiberius/issues/83
> Handle env change Routing request

- Cargo.toml
- src/error.rs
- src/tds/codec/batch_request.rs
- src/tds/codec/column_data.rs
- src/tds/codec/login.rs
- src/tds/codec/rpc_request.rs
- src/tds/xml.rs
- tests/query.rs
... so let's use that for better support of emojis and all that.
> We should be able to use UTF-16

- .buildkite/pipeline.sh
- .buildkite/publish_rustdoc.sh
- Cargo.toml
- README.md
- src/client/auth.rs
- src/error.rs
- src/lib.rs
- src/tds/codec/batch_request.rs
- src/tds/codec/column_data.rs
- src/tds/codec/token/token_sspi.rs
- src/tds/context.rs
- src/tds/numeric.rs
- src/tds/time.rs
- src/tds/time/chrono.rs
- src/to_sql.rs
- tests/query.rs
- Support for `BigDecimal` conversions
- Enabling feature flag documentation
> Bigdecimal support

- src/tds/codec/column_data.rs
- tests/query.rs
Seems that if the columns are `NOT NULL`, we must handle `money` and `smallmoney` as fixed size.
> Fixing panicky money types, when size is fixed

- tests/query.rs
In reply to https://github.com/prisma/tiberius/issues/119
> Test that we can read and write tinyints

- Cargo.toml
- src/client.rs
- src/client/connection.rs
- src/result.rs
- src/tds/codec/login.rs
- src/tds/codec/rpc_request.rs
- src/tds/codec/token/token_col_metadata.rs
- src/tds/codec/token/token_done.rs
- src/tds/stream/query.rs
Make login message fields private with setters. Set the default trait for it. Document all flags.
> Switch from bitflags to enumflags2

- src/tds/codec/column_data.rs
- src/tds/collation.rs
Helping to solve errors such as https://github.com/prisma/prisma/issues/6169
> Add info of LCID and sort id to colation errors

- .github/workflows/test.yml
- src/tds/codec/login.rs
- src/tds/codec/rpc_request.rs
- src/tds/codec/token/token_done.rs
> Unified bitflag setup

- src/client/auth.rs
- src/client/config.rs
- src/client/config/ado_net.rs
- src/sql_browser/async_std.rs
- src/sql_browser/tokio.rs
- src/tds/codec/token/token_info.rs
- src/tds/numeric.rs
- src/tds/xml.rs
- If using SQL Browser, default to 1434
- If not, default to 1433
If SQL Browser times out, give a better error about what's going on.
Helps with confusion, e.g. on ticket https://github.com/prisma/prisma/issues/6845
> Correct default ports

- Cargo.toml
- src/tds/codec/login.rs
- src/tds/codec/rpc_request.rs
- src/tds/codec/token/token_col_metadata.rs
- src/tds/codec/token/token_done.rs
> Update to enumflags2 0.7

- .github/workflows/test.yml
> Do not exit in sql server installation

- src/client/connection.rs
This should improve runtime operation in cases where the network is not fast enough. The old implementation would force the runtime to poll again, and the new one lets the socket to do that when there's data.
Closes: https://github.com/prisma/tiberius/issues/170
> Skip unnecessary waker calls.

- src/client.rs
> show TokioAsyncWriteCompatExt in Client docs

- LICENSE-APACHE.txt
- LICENSE-MIT.txt
This was definitely copied by somebody who's not me from a repo with an owner who never has contributed to Tiberius (even though he's a superb dev).
> Remove copypasta

- .github/workflows/test.yml
- Cargo.toml
- README.md
- src/lib.rs
- src/tds.rs
- src/tds/codec/column_data/date.rs
- src/tds/codec/column_data/datetime2.rs
- src/tds/codec/column_data/datetimen.rs
- src/tds/codec/column_data/datetimeoffsetn.rs
- src/tds/codec/column_data/time.rs
- src/tds/sql_time.rs
- src/tds/sql_time/chrono.rs
- src/tds/sql_time/time.rs
- tests/query.rs
Closes: https://github.com/prisma/tiberius/issues/190
> Support for time crate 0.3.x

- Cargo.toml
- README.md
- src/client.rs
- src/client/connection.rs
- src/client/tls.rs
- src/client/tls_stream.rs
based on the feedback, enable rustls under a feature use_rustls
> create a feature flag for rustls integration

- .github/workflows/test.yml
- Cargo.toml
- README.md
- src/client/tls_stream.rs
- src/client/tls_stream/opentls_tls_stream.rs
If rustls won't work, this one will fix issues on macOS platforms.
Part of https://github.com/prisma/prisma/issues/13371, https://github.com/prisma/prisma/issues/13372 and https://github.com/prisma/prisma/issues/13522
> Add option to vendor OpenSSL

- src/sql_browser.rs
> Fix SQL Browser response parsing error

- Cargo.toml
- src/tds/codec/column_data.rs
- src/tds/codec/token/token_col_metadata.rs
- tests/bulk.rs
The solved problem described in issue #234
> add fractional seconds precision for datetime2

- src/tds/stream/token.rs
We should take the first error from the wire, which is the one holding most of the interesting information.
Hotfix for a new regression.
> Fix error ordering

- src/tds/numeric.rs
Discovered while working on https://github.com/prisma/client-planning/issues/237
`10i64.pow(u32::try_from(exp.abs())` overflowed for large numbers. The public BigDecimal API splits the computation and performs the power on a `BigInt` to avoid this overflow.
https://github.com/akubera/bigdecimal-rs/blob/master/src/lib.rs#L76-L94
Let me know if you think it's better to own this code. There's no public issue because this was discovered while working on JSON protocol which lifted some GQL int boundary limitation and made it possible to cross this code path. Specifically, it made [this test](https://github.com/prisma/prisma-engines/blob/e903be1b16f0374d6fa09aa62987d9ebb38ebcbf/query-engine/connector-test-kit-rs/query-engine-tests/tests/new/regressions/max_integer.rs#L737-L778) fail.
> fix: bigdecimal conversion overflow
