prisma/tiberius

tiberius/Cargo.toml
tiberius/examples/new.rs
tiberius/src/async_read_le_ext.rs
tiberius/src/client.rs
tiberius/src/client/connection.rs
tiberius/src/lib.rs
tiberius/src/protocol/codec.rs
tiberius/src/protocol/codec/column_data.rs
tiberius/src/protocol/codec/token/token_col_metadata.rs
tiberius/src/protocol/codec/token/token_done.rs
tiberius/src/protocol/codec/token/token_env_change.rs
tiberius/src/protocol/codec/token/token_error.rs
tiberius/src/protocol/codec/token/token_info.rs
tiberius/src/protocol/codec/token/token_login_ack.rs
tiberius/src/protocol/codec/token/token_order.rs
tiberius/src/protocol/codec/token/token_return_value.rs
tiberius/src/protocol/codec/token/token_row.rs
tiberius/src/protocol/codec/token/token_sspi.rs
tiberius/src/protocol/codec/token/token_type.rs
tiberius/src/protocol/codec/type_info.rs
tiberius/src/protocol/stream/prepared.rs
tiberius/src/protocol/stream/query.rs
tiberius/src/protocol/stream/token.rs
tiberius/tests/query.rs

Instead of polling until we get enough packets for the token, while approximating its size, we implement `AsyncRead` for the connection, that buffers packets when needed and allows decoders to read bytes from it. This fixes problems with tokens of unknown size, such as `TEXT` or `XML`.

Async read version

---

src/client.rs
src/result.rs
src/tds/stream/prepared.rs
src/tds/stream/query.rs
src/tds/stream/token.rs
tests/query.rs

I've created a new pull request and will close the old one (This one has a proper rebase :D)
Changes here:
* `ExecResult` now stores a `Vec<u64>`
* Avoided the unsafe in `ExecResult::new` in the previous PR by using the same tactic as in query.rs (` let this = self.get_mut();` and then `poll_next_unpin` for `TokenStream`'s `impl Stream`)

Exec result v2

---

examples/new.rs
src/client/connection.rs
src/tds/codec/token/token_sspi.rs
src/tds/stream/token.rs

This will fix compilation errors, but now it seems `EncryptionMode::Off` is just stalling if using Windows auth. Really need to get the AppVeyor tests working soon to catch these.

Fix Windows issues with integrated login for certain encryption modes

---

src/result.rs
src/tds/stream/query.rs
tests/query.rs

The `QueryResult` mapped column names only, we should return the actual column struct for being comparable with the API in `Row`.

QueryResult should return columns as &[Column]

---

src/client.rs
src/result.rs
src/row.rs
src/tds/codec.rs
src/tds/codec/batch_request.rs
src/tds/codec/header.rs
tests/query.rs

This will skip preparing a statement, which is useful for certain queries that cannot be executed as statements.

A way to execute simple queries

---

src/tds/codec/column_data.rs
src/tds/codec/type_info.rs
tests/query.rs

Columns of type `char` was panicking before this change.

Fix handling of char

---

src/client/connection.rs

I was connecting to Azure SQL and realized that it was failing once I turned off TrustServerCert, this should fix the issue

pass hostname to tls_handshake

---

src/from_sql.rs
src/tds/codec/column_data.rs
src/tds/codec/token/token_col_metadata.rs
src/to_sql.rs
tests/query.rs

It was mistakenly handled as `i8`, even though the documentation says it's from 0 to 255, meaning `u8`.

Fixing `tinyint` encode/decode

---

src/tds/context.rs
tests/query.rs

closes #68 
* This makes the desired wrapping behavior explicit 
* This potentially causes a very small performance cost - an alternative would be to document that doing many queries in debug builds can cause a panic

make packet_id wrapping explicit

---

Cargo.toml
README.md
src/client/auth.rs
src/client/builder.rs
src/client/connection.rs
src/error.rs
src/lib.rs
src/tds/codec/token.rs
src/tds/codec/token/token_sspi.rs
src/tds/context.rs
src/tds/stream/token.rs

This PR leverages the libgssapi crate to provide IntegratedSecurity support via Kerberos on Unix.
At the TDS protocol level, all the SSPI tokens/packets/etc are used for this, too, so I turned off the cfg(windows) for all of that machinery, and added the libgssapi dependency as cfg(unix). From a dependency perspective, though, could be nice to make it a dependency folks can turn off. Happy to adjust.
Anyhow, have a look and let me know what else this needs, if anything -- tested in a ActiveDirectory-based Kerberos environment with SQL Server.

Use GSSAPI for IntegratedSecurity on Unix

---

README.md

As a follow-up to the gssapi integration, @edmellum tried to use the feature on MacOS and it failed. After some effort on that crate (see estokes/libgssapi#2), it now uses Apple's official GSSAPI libraries and no longer needs any third-party libraries to work.
This PR updates the README to reflect this change.
One other note, it might be worthwhile to add `default_features = false` for the libgssapi dependency going forward, since the default features include some things that are not available on Mac but that this integration doesn't use anyhow.

Reflect tweaks to upstream libgssapi crate

---

src/client/builder.rs
tests/query.rs

If `encrypt=DANGER_PLAINTEXT`, TLS encryption will be disabled completely.
This is super dangerous over any public or private network, so use sparingly. Should help mac users who can't connect to SQL Servers running incompatible TLS certificates.

Allow disabling TLS in connection string

---

Cargo.toml
src/client/builder.rs
src/error.rs

This replaces our `str.split(';')` parsing with a parser that's aware of escape sequences. This is required for correctly handling passwords that contain `;` characters. Thanks!

Use connection-string for ado.net parsing

---

README.md

The connection string key is `encrypt`, not `encoding`:
https://github.com/prisma/tiberius/blob/560b7fa9/src/client/config.rs#L256
Thanks for documenting this workaround!

Change "encoding" to "encrypt" in README

---

Cargo.toml
src/error.rs
src/tds/codec/batch_request.rs
src/tds/codec/column_data.rs
src/tds/codec/login.rs
src/tds/codec/rpc_request.rs
src/tds/xml.rs

- Allocates less: writes while encoding.
- Does not iterate all for getting the number of bytes.
- Uses ucs2 crate

Lean and faster string writes

---

src/tds/codec/token/token_done.rs
src/tds/stream/query.rs
tests/query.rs

If executing multiple statements, we must stream all results. The `Done` token holds information for later results, and we must not stop fetching until we have no more data left in the wire.

Handle all MARS results properly

---

src/client.rs
src/tds/codec/batch_request.rs
src/tds/codec/rpc_request.rs
src/tds/codec/token/token_env_change.rs
src/tds/context.rs
src/tds/stream/query.rs
src/tds/stream/token.rs

Fixing three bugs.
This fixes a problem where we might have warnings coming before errors in multiple resultset queries, when executing with `simple_query`.
Example:
```sql
CREATE UNIQUE INDEX [X] ON [table] ([column]);
```
In this case, if our column breaks unique validations, we'd expect `simple_query` to return an error.
If the column is of type `varchar` and the length is above threshold, the first token we get back is a warning of index size. We used to stop fetching data at this point, and our query would be successful even though we actually had an error in the wire.
Only the `BeginTransaction` holds the descriptor. Commit, rollback et.al. do not hold any data, and we can just zero the descriptor if having these events.
This has been causing weird bugs when running MARS with …

Do not swallow errors in simple query. Fixing transaction descriptors. Read envchanges correctly.

---

src/tds/time/chrono.rs

Previously the offset was subtracted from the time, before the date and
time were used to create a NaiveDateTime object. Then after the
NaiveDateTime object was created the offset was "added" again by means of
the `from_utc` method.
The problem with this approach is that if the offset is greater the
the time, you should actually go back a day in time. But since this action
was only done on the time, the date was not changed. So when the offset
was "added" again, the clock moved forward and added an additional day.
For example this object:
```rust
DateTimeOffset {                                                                                                                                                                   │[I] ao …
```

Fix a time conversion error

---

src/sql_read_bytes.rs
src/tds/codec.rs
src/tds/codec/column_data.rs
src/tds/codec/token/token_col_metadata.rs
src/tds/codec/token/token_error.rs
src/tds/codec/token/token_info.rs
src/tds/codec/token/token_login_ack.rs
src/tds/codec/token/token_return_value.rs
src/tds/codec/type_info.rs

- `read_b_varchar` reads a u8-prefixed string from the wire.
- `read_us_varchar` reads a u16-prefixed string from the wire.

Implement reader functions for string data

---

src/client/config.rs
src/client/config/ado_net.rs
src/client/config/jdbc.rs

The database is now parsed from the following keys:
- database
- databaseName
- initial catalog
All keys case-insensitive.
Closes: https://github.com/prisma/tiberius/issues/99

Add databaseName to the allowed keys in conn str

---

Cargo.toml
README.md
src/client/connection.rs
src/client/tls.rs
src/error.rs

Closes: https://github.com/prisma/tiberius/issues/65

Use OpenSSL on macOS systems

---

Cargo.toml
src/client/config.rs
src/client/config/ado_net.rs
src/client/config/jdbc.rs
src/client/connection.rs
src/client/tls.rs
src/error.rs
src/tds.rs
src/tds/codec/pre_login.rs
tests/query.rs

Users can always not use TLS by setting a runtime parameter. This makes all feature flags much more straightforward. Otherwise we'd always build opentls even if we need native-tls, or always build native-tls even if needing opentls. And now we can also set the correct runtime feature for async-native-tls or opentls, so we don't need to build tokio if using async-std and so on...

Always compile with TLS

---

README.md
src/client/connection.rs
src/tds/codec/decode.rs
src/tds/codec/encode.rs
src/tds/codec/login.rs

This fixes a few things. First, connections to Azure SQL managed instances were not possible before. It complained we didn't set the server name with the user, even though our username was set as `user@server_name`. We actually need to specify the server name in the login packet too. I was able to connect successfully to the managed instance using this patch.
The second is the problem of redirects. In a case where we error on connect with:
```
Error: Server requested a connection to an alternative address: `asdf.database.windows.net:11006`
```
We should then modify our configuration to point to the new address, and try again. With this patch, this actually works and we can close https://github.com/prisma/tiberius/issues/88.

Set server name in the login packet

---

Cargo.toml
src/sql_browser/async_std.rs
src/sql_browser/tokio.rs

On SQL Browser, we previously just tried the first resolved IP, and failed with connection refused if it didn't work. Now there's a docker bug that doesn't allow us to connect with `::1`, meaning using `localhost` with the docker image would tehn try to connect to `::1`, fail and stop the world.
Now we look into other addresses too, and try again if the first ones didn't work.

Try out all resolved IP addresses

---

.envrc
.gitignore
Cargo.toml
shell.nix

If using Nix/NixOS, adds the needed shell environment to compile all features of Tiberius.
Either run
```bash
> nix-shell develop
```
or if using direnv, enable nix/shell integrations with home-manager:
```nix
direnv = {
enable = true;
enableFishIntegration = true;
enableNixDirenvIntegration = true;
};
```

Nix shell setup

---

src/row.rs
src/tds/stream/query.rs
tests/query.rs

In some cases queries can trigger warnings, and this lead to faulty metadata (e.g. missing columns).
Closes: https://github.com/prisma/tiberius/issues/133

Warnings should not affect metadata fetching

---

src/client/config.rs
src/client/config/ado_net.rs

Support for parsing "integratedsecurity" was already done correctly. I have added the possibility to parse "integrated security" as well.
The tests have been modified to check if it works correctly.

Add Config parsing for "Integrated Security" (two words)

---

src/client/config.rs

Sql Browser works fine on non-windows platforms (at least Linux), so there is no reason to limit parsing out the instance name to Windows.

Parse instance name from ADO connection string, regardless of platform

---

src/client/config.rs
src/client/config/ado_net.rs
tests/query.rs

Multiple fixes:
- Parse of `data source=` in AdoConfig which is the same as `server=`
- Support for dot syntax: `.` which is the same as `localhost`
- Fix crash when port is missing inside the server address. Fallback on the default port which are:
- 1433 for std tcp connection
- 1434 for resolving instances
I have add tests to reflect the changes.

Add data source, dot syntax for server and fix crash when port is missing (fallback on the default port)

---

src/tds/codec/column_data.rs
src/tds/codec/token/token_col_metadata.rs
src/tds/codec/type_info.rs
src/tds/collation.rs
tests/query.rs

So... Everybody uses the N variants to store non-ASCII data? No?
This fixes some wild assumptions:
- `CHAR` has always only ASCII data
- And `TEXT` too.
If not, well, of course the user uses `NCHAR` and `NTEXT`, right?
So, instead of just blindly converting the data to UTF-8, we actually use the given collation codepage, and use it to translate the string to UTF-8.
Part of fixing: https://github.com/prisma/prisma/issues/7476

Handle collations for CHAR and TEXT values

---

src/row.rs
src/tds/codec/column_data.rs
src/tds/codec/column_data/binary.rs
src/tds/codec/column_data/bit.rs
src/tds/codec/column_data/date.rs
src/tds/codec/column_data/datetime2.rs
src/tds/codec/column_data/datetimen.rs
src/tds/codec/column_data/datetimeoffsetn.rs
src/tds/codec/column_data/fixed_len.rs
src/tds/codec/column_data/float.rs
src/tds/codec/column_data/guid.rs
src/tds/codec/column_data/image.rs
src/tds/codec/column_data/int.rs
src/tds/codec/column_data/money.rs
src/tds/codec/column_data/plp.rs
src/tds/codec/column_data/string.rs
src/tds/codec/column_data/text.rs
src/tds/codec/column_data/time.rs
src/tds/codec/column_data/var_len.rs
src/tds/codec/column_data/xml.rs
src/tds/codec/token/token_col_metadata.rs
src/tds/codec/type_info.rs

- Some repetition removed.
- The monster `column_data.rs` is now split.
- PLP decoding simplified, like a lot
- TEXT and NTEXT column handling should be faster, we don't initialize a vector of zeroes before reading the data!

Split column decoding into modules

---

src/client/config.rs
src/client/config/ado_net.rs
src/client/config/jdbc.rs
src/client/connection.rs
src/tds/codec/login.rs
tests/query.rs

Available from Config method `application_name` and in the JDBC and ADO.net strings either with `Application Name` or
`ApplicationName` (case-insensitive).
Closes: https://github.com/prisma/tiberius/issues/159

Allow setting application name per connection

---

Cargo.toml
src/tds/numeric.rs
tests/query.rs

Fixes a dependency version conflict on Quaint by using the bundled and exposed version of `num_bigint` by `bigdecimal`.

fix: use bundled bigint from bigdecimal

---

.github/workflows/test.yml
rust-toolchain

- Rename `master` to `main`
- Add `rust-toolchain` file for (more) reproducible builds with a pinned Rust version
- Remove `toolchain` from GH Actions so value from `rust-toolchain` is used instead
- Remove GH Actions matrixes for toolchain version as unused and to enable picking up from `rust-toolchain` as well

Prepare renaming of main branch from master to main

---

Cargo.toml

`git grep async_stream` returns no matches.

Remove unused async-stream dep

---

Cargo.toml
src/tds/codec/token/token_done.rs
src/tds/codec/token/token_info.rs
src/tds/codec/token/token_login_ack.rs
src/tds/codec/token/token_order.rs

The 0.4 version of async-native-tls just uses `futures-util` instead of `async-std`, allowing us to get rid of `async-std` if using tokio runtime.
https://github.com/async-email/async-native-tls/blob/master/Cargo.toml#L30
Helps with: https://github.com/prisma/prisma-engines/pull/2562

Remove async-std from deps if using tokio

---

src/tds/codec/pre_login.rs

Defined in: https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-tds/60f56408-0188-4cd5-8b90-25c6f2423868
Part of: https://github.com/prisma/prisma/issues/11009

Add support for all pre-login tokens

---

src/client/auth.rs
src/client/config.rs
src/client/connection.rs

Currently, building without default features fails on windows because
there are feature gated includes used in non-gated code that were missed
in a8ae150c4988366f3f96ad4755db3b5a3d70a95c.

Add missing winauth feature gates

---

src/client.rs
src/lib.rs
src/macros.rs
src/query.rs
src/row.rs
src/tds/numeric.rs
src/tds/time/chrono.rs
src/to_sql.rs
tests/query.rs

Introduces a new API to perform queries that bind dynamic parameters, making
them easier without needing to cast dyn traits out of the data before using.
The public API is the `Query` struct:
- Initialize with the query string
- Bind parameters one by one
- Either query or execute with a connection
Extends the `IntoSql` implementations to all types, making the binding
by-value, but allowing using references if needed.
In the end, might be we want to remove the `ToSql` completely, but not yet.

Dynamic query interface

---

src/tds/codec/column_data.rs
src/tds/codec/column_data/float.rs
src/tds/codec/column_data/int.rs
src/tds/codec/column_data/var_len.rs
tests/query.rs

Related to https://github.com/prisma/prisma/issues/12796 and https://github.com/prisma/prisma/issues/12798
- All null integers, regardless of their type length, were decoded as `u8`. This causes `quaint` to read null `bigint` as `Int32(None)` instead of `Int64(None)`.
- Same goes for floats. Not sure it's causing any issue atm since we're not differentiating `f32` vs `f64` in the rest of the "Prisma stack", but I did it anyway for good measure.
There were existing tests reading nullable integers, but those tests were only trying to convert the `ColumnData` to a rust primitive type and assert that primitive type. However, because of those `FromSql` implementations 👇 which enable converting a `ColumnData::U8` and `ColumnData::I32` to an `Option<i64>`, tests were passing.
I left those …

fix: correctly decode null integers & floats

---

.github/workflows/test.yml
Cargo.toml
README.md
src/client.rs
src/client/config.rs
src/client/config/ado_net.rs
src/client/config/jdbc.rs
src/client/connection.rs
src/client/tls.rs
src/client/tls_stream.rs
src/client/tls_stream/native_tls_stream.rs
src/client/tls_stream/rustls_tls_stream.rs
src/error.rs
src/tds/codec/pre_login.rs
tests/custom-cert.rs

- We do not need hyper for one TLS extension.
- Modules into files.
- Feature flags `native-tls` and `rustls`.
- Docs change
- CI flag changes

Cut down deps, make TLS optional

---

README.md

- List which editions have TCP enabled by default
- update links with docs.microsoft.com instead of legacy Technet

README.md: precisions when TCP should be enabled

---

Cargo.toml

The `uuid` crate recently had its first stable release.

Upgrade to uuid v1.0

---

Cargo.toml
flake.lock
src/client.rs
src/client/connection.rs
src/sql_browser.rs
src/tds/codec.rs
src/tds/codec/column_data.rs
src/tds/codec/token/token_row.rs
src/tds/numeric.rs
src/tds/stream/query.rs
tests/query.rs

This patch fixes an issue with writing `BigDecimal` values to the `decimal`/`numeric` column type in SQL Server. The server numeric is a combination of two numbers: a signed 128-bit integer for the value itself and an unsigned 8-bit integer to define the position of the point in the number.
So a number such as `9.123` is stored as `9123_i128` with `3` as the scale. You count three numbers to the left from the right, and put the point between numbers `9` and `1`.
The `BigDecimal` library handles the scale as a signed integer. In that library, a number `9000` can be written either as `9000` with `0` as the scale, or as `9` with `-3` as the scale which signals us that we have to move the point to the right from the right, adding zeroes to the actual value. So in this case we move the point …

Handle negative scale from a BigDecimal

---

Cargo.toml
flake.lock
flake.nix
src/client/auth.rs
src/client/config/ado_net.rs
src/error.rs
src/macros.rs
src/result.rs
src/row.rs
src/tds/codec/login.rs
src/tds/codec/rpc_request.rs
src/tds/codec/token/token_col_metadata.rs
src/tds/codec/token/token_done.rs
src/tds/codec/token/token_error.rs
src/tds/codec/type_info.rs
src/tds/collation.rs
src/tds/stream/token.rs
src/tds/xml.rs
tests/deadlocks.rs
tests/login_errors.rs

We have to consume the whole token stream to the end even if having an error. Error is stored to the stream, and further tokens are all handled before responding to the user.
This way a possible rollback can zero the transaction descriptor, and the connection can be used for further queries without an error.

Propagate errors correctly

---

src/tds/codec/token/token_col_metadata.rs
tests/query.rs

If SQL Server decides to optimize row null values, we should return the correctly typed `None` value for differently sized integers and floating points.
Closes: https://github.com/prisma/tiberius/issues/249

Fix null values in NBC rows

---

src/tds/codec/token/token_row.rs

- `with_capacity` doesn't need self as a parameter
- Add a `clear` method
Closes: https://github.com/prisma/tiberius/issues/254

Cleanup TokenRow public API

---

src/client/config/ado_net.rs

It's a common practice to work with keyword `(local)` on "server/data source" name, specially with docker based sql server solutions.
Since it's not directly recognized as server name we can replace it with `localhost `instead to make it work fine

Correctly parse (local) server name

---

src/client.rs
src/client/connection.rs

This PR adds a method allowing users to close the connection explicitly and wait until it is closed.

Close connection explicitly

---

Cargo.toml

To disable the dependency on time 0.1, set chrono `default-features = false`.
- https://github.com/chronotope/chrono/issues/602#issuecomment-1225331424

Disable chrono's oldtime feature

---

src/client/config.rs
src/client/connection.rs
src/tds/codec/login.rs

In our production environment, we use Always On availability groups and availability group listeners. However, tiberius does not support connecting to readonly replicas, preventing us from utilizing readonly replicas.
To connect to readonly replica via availability group listener, we should specify `ApplicaitonIntent=ReadOnly` in connection string[^1]. It sets `TypeFlags`' `fReadOnlyIntent` bit[^2].
This PR makes tiberius to support `ApplicationIntent=ReadOnly`.
[^1]: https://learn.microsoft.com/en-us/sql/database-engine/availability-groups/windows/configure-read-only-routing-for-an-availability-group-sql-server?view=sql-server-2017
[^2]: https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-tds/773a62b6-ee89-4c02-9e5e-344882630aac

Send ReadOnlyIntent when ApplicationIntent=ReadOnly specified

---

src/row.rs
src/tds/codec/token/token_row.rs

It is currently possible to iterate over `Row` objects, but only through `.into_iter()` which means the borrow checker will not also let us look at the columns. Thus, it is hard to write generic code that operates on any `Row` object.
This PR exposes a `.cells()` method which allows immutable iteration over the `Row` object. It also exposes a public constructor for `Row` objects so that we can write tests for such generic code.
This addresses the iteration half of prisma/tiberius#278.

Allow iterating over the cells in a row

---

Cargo.toml
src/client/connection.rs

When using AuthMethod::IntegratedSecurity on Windows, the library behaves just as you would expect. However, when I tried to run my code on a Linux machine with proper Kerberos authentication set up, I would always get the following panic message when run in debug mode (`cargo run --debug`):
```
thread 'tokio-runtime-worker' panicked at library\core\src\panicking.rs:220:5:
unsafe precondition(s) violated: slice::from_raw_parts requires the pointer to be aligned and non-null, and the total size of the slice not to exceed `isize::MAX`
``` 
Due to changes in the standard library (see [https://stackoverflow.com/a/78504630](https://stackoverflow.com/a/78504630) ), it is possible for debug assertions in `core` and `std` to panic: These assertions now fire when compiled in debug mode, even if …

Fix GSSAPI Kerberos Authentication in Debug Mode
